INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (1, 'default', NULL, 'category', NULL, 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (6, 'my github', 'https://github.com/zhisheng17', 'link', 'http://www.54tianzhisheng.cn/img/avatar.png', 1, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (7, 'my website', 'http://www.54tianzhisheng.cn', 'link', 'http://www.54tianzhisheng.cn/img/avatar.png', 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (8, '随笔', '随笔', 'tag', NULL, 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (9, 'Java', 'Java', 'tag', NULL, 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (10, 'Java', 'Java', 'category', '有关Java的博客', 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (11, 'HashMap', 'HashMap', 'tag', NULL, 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (12, 'HashTable', 'HashTable', 'tag', NULL, 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (13, 'HashSet', 'HashSet', 'tag', NULL, 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (14, 'ConcurrentHashMap', 'ConcurrentHashMap', 'tag', NULL, 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (15, 'Pyspider', 'Pyspider', 'tag', NULL, 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (16, 'Python', 'Python', 'tag', NULL, 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (17, '爬虫', '爬虫', 'tag', NULL, 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (19, 'Python', 'Python', 'category', '有关Python的博客', 0, 0);
INSERT INTO `t_metas`(`mid`, `name`, `slug`, `type`, `description`, `sort`, `parent`) VALUES (20, '随笔', NULL, 'category', NULL, 0, 0);
